version: '3.7'
services:

  db:
    image: postgres:15
    env_file:
      - src/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - static_data:/app/src/static
    env_file:
      - src/.env
    ports:
      - '8000:8000'

  nginx:
    image: nginx:1.19.8
    depends_on:
     - app
    ports:
      - '80:80'
    volumes:
      - static_data:/var/www/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pgdata:
  static_data:
