# Generated by Django 5.1.1 on 2024-09-16 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('created', models.DateField(default='2024-09-16')),
                ('due_date', models.DateField(default='2024-09-16', verbose_name='Дата завершения задачи')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='task.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category'),
        ),
    ]
