# Generated by Django 5.1.1 on 2024-09-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default='2024-09-16, 11:10'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='2024-09-16, 11:10', verbose_name='Дата завершения задачи'),
        ),
    ]
