# Generated by Django 5.1.1 on 2024-09-16 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_created_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 11, 38, 51, 714725, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 11, 38, 51, 714745, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения задачи'),
        ),
    ]
