version: '3.7'
services:

  db:
    image: postgres:15
    env_file:
      - src/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5434'

  app:
    build:
      context: .
    command: sh -c "gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8040 main:app"
    depends_on:
      - db
    env_file:
      - src/.env
    ports:
      - '8040:8040'

  nginx:
    image: nginx:1.19.8
    depends_on:
     - app
    ports:
      - '8080:8080'
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pgdata:
